name: Build and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Lint commit messages
      uses: wagoid/commitlint-github-action@v5
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install Packages
      run: npm install --prefer-offline --no-audit
    - name: Build
      run: npm run build
    - name: Lint
      run: npm run lint
    - name: Run unit tests
      run: npm test
    - name: Build documentation
      run: npm run docs
    - name: Upload code coverage to codecov
      uses: codecov/codecov-action@v3

  publish:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install Packages
      run: npm install --prefer-offline --no-audit
    - name: Build
      run: npm run build
    - name: Build documentation
      run: npm run docs
    - name: Set git credentials
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Set npm credentials
      run: echo //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN > ~/.npmrc
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Publish
      uses: cycjimmy/semantic-release-action@v3
      with:
        semantic_version: 17
        branches: main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
